// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHntFXbN1d11dV5NAvZ5Gm3tbimwD63Dg',
    appId: '1:404478966588:web:fca8634e19cacd3d9ebc39',
    messagingSenderId: '404478966588',
    projectId: 'uni-navigator-9be42',
    authDomain: 'uni-navigator-9be42.firebaseapp.com',
    storageBucket: 'uni-navigator-9be42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Dv2AvJCZMRoEjVCfiH-Hv00JXKE8oUs',
    appId: '1:404478966588:android:849381470b172f429ebc39',
    messagingSenderId: '404478966588',
    projectId: 'uni-navigator-9be42',
    storageBucket: 'uni-navigator-9be42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgBApK0uMNrSWh1muDiRXWs4Y1BTwRlDs',
    appId: '1:404478966588:ios:4ef0751109f9a6549ebc39',
    messagingSenderId: '404478966588',
    projectId: 'uni-navigator-9be42',
    storageBucket: 'uni-navigator-9be42.appspot.com',
    iosBundleId: 'com.example.nsbm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgBApK0uMNrSWh1muDiRXWs4Y1BTwRlDs',
    appId: '1:404478966588:ios:da3429dc3bb992d09ebc39',
    messagingSenderId: '404478966588',
    projectId: 'uni-navigator-9be42',
    storageBucket: 'uni-navigator-9be42.appspot.com',
    iosBundleId: 'com.example.nsbm.RunnerTests',
  );
}
